spring:
  data:
    mongodb:
      #host: localhost
      #port: 27017
      #database: smarthouse
      #authentication-database: admin

      uri: mongodb+srv://root:root@atlascluster.ltf1m.mongodb.net/Academie?retryWrites=true&w=majority
server:
  port: ${PORT:8080}


